from site_helpers import *
import json
articles=[]
for filename in ['articles-1.json','articles-2.json']:
    articles+=json.loads((ROOT/'scripts/site-data'/filename).read_text(encoding='utf-8-sig'))
assert len(articles)==10 and len({a['slug'] for a in articles})==10
categories={'payroll':('Payroll','Payroll'),'recruitment':('สรรหาบุคลากร','Recruitment'),'organization':('ระบบ HR และองค์กร','HR & organization'),'digital':('Digital HR','Digital HR'),'events':('กิจกรรมองค์กร','Corporate events')}

def article_card(a,index=0):
    cat=categories[a['category']]
    return f'''<article class="insight-card" data-article-category="{a['category']}"><a class="insight-visual visual-{a['category']}" href="{a['slug']}.html" aria-hidden="true" tabindex="-1">{icon(a['icon'])}<span>INSIGHT / {index+1:02}</span><i aria-hidden="true"></i></a><div class="insight-card-body"><span class="insight-category">{t(*cat)}</span><h2><a href="{a['slug']}.html">{t(*a['title'])}</a></h2>{t(*a['summary'],tag='p')}<a class="insight-read" href="{a['slug']}.html">{t('อ่านบทความ','Read article')} <span aria-hidden="true">↗</span></a></div></article>'''
filter_buttons='<button type="button" data-category="all" aria-pressed="true">'+t('ทั้งหมด','All')+'</button>'+''.join(f'<button type="button" data-category="{key}" aria-pressed="false">{t(*label)}</button>' for key,label in categories.items())
body=f'''<section class="pricing-hero insights-hero"><div class="ms-container"><span class="ms-eyebrow">PEOPLE / KNOWLEDGE / GROWTH</span>{t('ความรู้เรื่องคน<br>สำหรับคนทำธุรกิจ','People insights.<br>For business minds.','h1')}{t('10 คู่มือสั้นเรื่อง Payroll การสรรหา ระบบ HR และเทคโนโลยี พร้อมแนวทางนำไปใช้และแหล่งอ่านต่อ','10 practical guides to payroll, recruitment, HR operations and technology, with actionable checklists and further reading.','p')}</div></section><section class="ms-section insights-section"><div class="ms-container"><div class="insights-toolbar"><div><span class="ms-eyebrow">EXPLORE THE LIBRARY</span>{t('เลือกเรื่องที่อยากเริ่ม','Find a useful starting point','h2')}</div><label class="insight-search">{icon('search')}<span class="visually-hidden">{t('ค้นหาบทความ','Search articles')}</span><input type="search" id="article-search" placeholder="ค้นหา เช่น Payroll หรือ Onboarding" data-en-placeholder="Search Payroll, onboarding, and more" maxlength="100"></label></div><div class="insights-filters" role="group" aria-label="Article categories">{filter_buttons}</div><p class="article-count" id="article-count" role="status" aria-live="polite">{t('แสดง 10 บทความ','Showing 10 articles')}</p><div class="insights-grid" id="articles-grid">{''.join(article_card(a,i) for i,a in enumerate(articles))}</div><div id="article-empty" class="article-empty" hidden>{icon('search')}{t('ยังไม่พบบทความที่ตรงกับคำค้น','No articles match your search','h3')}{t('ลองใช้คำสั้นลง หรือเลือกหมวดทั้งหมด','Try a shorter search or select all categories.','p')}<button type="button" class="ms-btn secondary" id="article-reset">{t('ล้างตัวกรอง','Reset filters')}</button></div></div></section>'''
(ROOT/'insights.html').write_text(shell('บทความ HR และธุรกิจ 10 เรื่อง',body,'insights.html','รวมคู่มือ HR Payroll Recruitment การดูแลข้อมูล เทคโนโลยี และกิจกรรมองค์กร พร้อมแหล่งอ้างอิง', '<script src="assets/insights.js?v=6" defer></script>'),encoding='utf-8')
for a in articles:
    sections=''.join(f'<section class="article-chapter" id="chapter-{i+1}">{t(*heading,tag="h2")}{t(*paragraph,tag="p")}</section>' for i,(heading,paragraph) in enumerate(a['sections']))
    toc=''.join(f'<a href="#chapter-{i+1}">{t(*heading)}</a>' for i,(heading,_) in enumerate(a['sections']))
    sources=''.join(f'<li><a href="{url}" target="_blank" rel="noopener noreferrer">{escape(name)} ↗</a></li>' for name,url in a['sources'])
    source_inline=' · '.join(f'<a href="{url}" target="_blank" rel="noopener noreferrer">{escape(name.split(" — ")[0])} ↗</a>' for name,url in a['sources'])
    checks=''.join(f'<li><span aria-hidden="true">✓</span>{t(*item)}</li>' for item in a['checklist'])
    related=sorted([x for x in articles if x['slug']!=a['slug']],key=lambda x:x['category']!=a['category'])[:3]
    body=f'''<div class="page-wayfinding"><div class="ms-container"><nav aria-label="Breadcrumb"><a href="index.html">{t('หน้าแรก','Home')}</a><span>/</span><a href="insights.html">{t('บทความ HR','HR insights')}</a><span>/</span>{t(*categories[a['category']])}</nav><a href="insights.html" class="back-pricing">← {t('กลับหน้าบทความ','All articles')}</a></div></div><article><header class="article-hero"><div class="ms-container"><span class="ms-eyebrow">{t(*categories[a['category']])}</span>{t(*a['title'],tag='h1')}{t(*a['intro'],tag='p')}<div class="article-meta">{t('คู่มือปฏิบัติ • เรียบเรียง 11 กันยายน 2026','Practical guide • Updated 11 September 2026')}<span>TH / EN</span></div></div></header><div class="ms-container article-layout"><aside class="article-toc"><strong>{t('ในบทความนี้','In this guide')}</strong>{toc}<a href="#checklist">{t('เช็กลิสต์นำไปใช้','Action checklist')}</a><a href="#sources">{t('แหล่งอ้างอิง','Sources')}</a></aside><div class="article-copy"><div class="article-principle"><span class="ms-eyebrow">THE STARTING POINT</span>{t(*a['principle'],tag='p')}<div class="article-source-inline">{source_inline}</div></div><p class="article-application-label">{t('แนวทางประยุกต์ใช้กับงานของคุณ','Practical application to your own work')}</p>{sections}<section class="article-checklist" id="checklist">{t('เช็กก่อนนำไปใช้','Before you put it into practice','h2')}<ul>{checks}</ul></section><section class="article-sources" id="sources">{t('แหล่งอ้างอิงและอ่านเพิ่มเติม','Sources and further reading','h2')}<ul>{sources}</ul>{t('เนื้อหาเรียบเรียงใหม่ พร้อมตัวอย่างและเช็กลิสต์สำหรับประยุกต์ใช้ ไม่ใช่การคัดลอกบทความต้นฉบับ','Original practical guidance with examples and checklists, informed by the sources above. This is not a reproduction of their articles.','p')}</section><div class="article-service-cta">{t('อยากปรับใช้กับองค์กรของคุณ?','Want to apply this in your organization?','h2')}{btn('พูดคุยเรื่องบริการ','Discuss your needs','request-quotation.html?service='+a['service'])}<a class="ms-text-link" href="{a['service']}.html">{t('ดูบริการที่เกี่ยวข้อง','Explore the related service')} ↗</a></div></div></div></article><section class="ms-section related-articles"><div class="ms-container"><div class="insights-toolbar">{t('อ่านต่อในเรื่องที่เกี่ยวข้อง','Continue exploring','h2')}<a href="insights.html" class="ms-text-link">{t('บทความทั้งหมด','All articles')} ↗</a></div><div class="insights-grid">{''.join(article_card(x,i) for i,x in enumerate(related))}</div></div></section>'''
    schema={'@context':'https://schema.org','@type':'Article','headline':a['title'][0],'description':a['summary'][0],'dateModified':'2026-09-11','mainEntityOfPage':'https://atibettop.github.io/OneStopService/'+a['slug']+'.html','publisher':{'@type':'Organization','name':'Muang Srisuk Group'},'citation':[url for _,url in a['sources']]}
    html=shell(a['title'][0],body,a['slug']+'.html',a['summary'][0],'<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>')
    (ROOT/(a['slug']+'.html')).write_text(html,encoding='utf-8')
# Add an entry to the library from the homepage, while preserving its hero and service content.
p=ROOT/'index.html';h=p.read_text(encoding='utf-8-sig')
if 'id="home-insights"' not in h:
    teaser=f'<section class="ms-section" id="home-insights"><div class="ms-container"><div class="insights-toolbar"><div><span class="ms-eyebrow">HR INSIGHTS</span>{t("ไอเดียที่นำไปใช้กับงาน HR ได้","Ideas you can put to work","h2")}</div><a class="ms-text-link" href="insights.html">{t("อ่านครบทั้ง 10 เรื่อง","Explore all 10 guides")} ↗</a></div><div class="insights-grid">'+''.join(article_card(x,i) for i,x in enumerate([articles[0],articles[1],articles[8]]))+'</div></div></section>'
    h=h.replace('<section class="ms-final">',teaser+'<section class="ms-final">',1)
p.write_text(h,encoding='utf-8')
(ROOT/'docs/article-sources.md').write_text('# Article sources — checked 11 September 2026\n\n'+ '\n'.join('## '+a['title'][0]+'\n\n'+a['slug']+'.html\n\n'+ '\n'.join('- ['+name+']('+url+')' for name,url in a['sources'])+'\n' for a in articles),encoding='utf-8')
