// Render English into real static HTML; run after prepare-release.py and the preview server.
const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');const fs=require('node:fs');
(async()=>{fs.mkdirSync('en',{recursive:true});const base=JSON.parse(fs.readFileSync('site-settings.json','utf8').replace(/^\uFEFF/,'')).baseUrl;const browser=await chromium.launch();for(const file of fs.readdirSync('.').filter(x=>x.endsWith('.html'))){const context=await browser.newContext();await context.route('**/site-config.js*',route=>route.fulfill({contentType:'application/javascript',body:fs.readFileSync('assets/site-config.js','utf8').replace(/const msLocalPreview = [^;]+;/,'const msLocalPreview = false;')}));await context.route('http://127.0.0.1:8090/OneStopService-V2/**',async route=>route.fulfill({response:await route.fetch({url:route.request().url().replace('/OneStopService-V2/','/')})}));const page=await context.newPage();await page.goto('http://127.0.0.1:8090/'+file+'?lang=en');await page.waitForTimeout(100);await page.evaluate(({base,file})=>{
 document.documentElement.lang='en';document.querySelector('base')?.remove();document.querySelector('link[rel=canonical]').href=base+'en/'+file;
 document.querySelectorAll('script').forEach(s=>{if(s.src.includes('i18n.js')||(!s.src&&!s.type&&s.textContent.includes('var asked')))s.remove();});
 for(const el of document.querySelectorAll('[href],[src]'))for(const attr of ['href','src']){const raw=el.getAttribute(attr);if(!raw||raw.startsWith('#')||/^(data:|mailto:|tel:)/.test(raw))continue;let url;try{url=new URL(raw,location.href);}catch{continue;}if(url.origin!==location.origin)continue;let path=url.pathname.replace(/^\/OneStopService-V2\//,'/').replace(/^\//,'').replace(/^en\//,'');if(path.startsWith('assets/')||path==='favicon.ico')el.setAttribute(attr,'../'+path+url.search);else if(path.endsWith('.html')){url.searchParams.delete('lang');el.setAttribute(attr,path+url.search+url.hash);}}
 document.querySelectorAll('[data-lang]').forEach(a=>{a.href=a.dataset.lang==='th'?'../'+file+'?lang=th':file+'?lang=en';});
 document.querySelectorAll('meta[property="og:url"]').forEach(x=>x.content=base+'en/'+file);
 document.querySelectorAll('script[type="application/ld+json"]').forEach(s=>{try{const d=JSON.parse(s.textContent);if(d['@type']==='Article'){d.headline=document.querySelector('h1').textContent;d.description=document.querySelector('meta[name=description]').content;d.mainEntityOfPage=base+'en/'+file;d.inLanguage='en';s.textContent=JSON.stringify(d)}}catch{}});
 document.querySelectorAll('.depth-enter').forEach(x=>x.classList.remove('depth-enter'));document.querySelectorAll('details[open]').forEach(x=>x.open=false);
 document.querySelectorAll('[data-en-content]').forEach(el=>el.removeAttribute('data-en-content'));
 },{base,file});fs.writeFileSync('en/'+file,await page.content());await context.close();}await browser.close();console.log('Exported 24 English pages.');})().catch(e=>{console.error(e);process.exit(1)});
