from site_helpers import *
import json
# Preserve the full original payroll scope for the comparison disclosure.
old=(ROOT/'pricing.html').read_text(encoding='utf-8-sig')
m=re.search(r'const FEATURES = (\[.*?\]);',old,re.S)
if m:
    (ROOT/'scripts/site-data/payroll-features.json').write_text(json.dumps(json.loads(m.group(1)),ensure_ascii=False,indent=2),encoding='utf-8')
hero=lambda label,th,en,sub,se: f'<section class="pricing-hero"><div class="ms-container"><span class="ms-eyebrow">{label}</span>{t(th,en,"h1")}{t(sub,se,"p")}</div></section>'
intro=hero('PRICING & PLANS','เลือกบริการที่ใช่<br>เห็นค่าใช้จ่ายก่อนตัดสินใจ','The right service.<br>A clearer view of the cost.','ประเมินราคาได้ทั้งงานเงินเดือนและงานสรรหาคน เลือกบริการด้านล่างเพื่อเริ่มคำนวณ','Estimate both payroll and recruitment costs. Choose a service below to get started.')
hub=f'''{intro}<section class="ms-section pricing-hub"><div class="ms-container"><div class="pricing-paths"><article class="pricing-path"><div class="path-art payroll-art">{icon('calc')}<span>PAYROLL / 01</span><div class="path-lines" aria-hidden="true"></div></div><div class="path-content"><span class="ms-eyebrow">PAYROLL OUTSOURCING</span>{t('ดูแลงานเงินเดือน','Payroll services','h2')}{t('กรอกจำนวนพนักงาน เปรียบเทียบ Lite, Pro และ Premium พร้อมดูยอดรายเดือนและประมาณการ 12 เดือน','Enter headcount and compare Lite, Pro and Premium, with monthly and 12-month estimates.','p')}<p class="path-start">{t('เริ่มต้น','From')} <strong>5,000</strong> {t('บาท/เดือน','THB/month')}</p><ul><li>{t('30 คนแรกคิดแบบเหมารายเดือน','Flat monthly fee for the first 30 employees')}</li><li>{t('จำนวนที่เกินคิดตามช่วงอัตราของแพ็กเกจ','Additional employees use the package’s headcount-band rate')}</li></ul>{btn('คำนวณค่าบริการ Payroll','Calculate payroll costs','payroll-calculator.html')}<a class="ms-text-link" href="payroll-outsourcing.html">{t('ดูขอบเขตบริการ Payroll','Explore payroll services')} ↗</a></div></article>
<article class="pricing-path"><div class="path-art recruitment-art">{icon('people')}<span>RECRUITMENT / 02</span><div class="path-orbits" aria-hidden="true"></div></div><div class="path-content"><span class="ms-eyebrow">RECRUITMENT SERVICES</span>{t('ค้นหาคนให้กับองค์กร','Recruitment services','h2')}{t('เลือกเหมารายเดือนสำหรับการรับคนต่อเนื่อง หรือ Success Fee ที่คำนวณตามรายได้รวมต่อปีของผู้เริ่มงาน','Choose a monthly retainer for ongoing hiring, or a success fee based on the new hire’s annual income.','p')}<p class="path-start">{t('รายเดือนเริ่มต้น','Retainers from')} <strong>9,900</strong> {t('บาท','THB')}</p><ul><li>{t('Starter / Professional / Business','Starter / Professional / Business')}</li><li>{t('Success Fee เริ่มที่ 15% ตามระดับตำแหน่ง','Success fees from 15%, depending on role level')}</li></ul>{btn('คำนวณค่าบริการสรรหาคน','Calculate recruitment costs','recruitment-calculator.html')}<a class="ms-text-link" href="recruitment.html">{t('ดูรายละเอียดและเงื่อนไข Recruitment','Recruitment scope & terms')} ↗</a></div></article></div><div class="pricing-help">{icon('chat')}<div>{t('ยังไม่แน่ใจว่าควรเลือกแบบไหน?','Not sure which option fits?','h3')}{t('เล่าจำนวนพนักงานหรือตำแหน่งที่ต้องการ เราช่วยประเมินขอบเขตให้เหมาะกับองค์กร','Tell us your headcount or hiring needs and we can assess the right scope.','p')}</div>{btn('ให้ทีมช่วยประเมิน','Ask our team','request-quotation.html',True)}</div><p class="ms-note">{t('ราคาที่แสดงเป็นประมาณการเบื้องต้น ภาษี ค่าใช้จ่ายเพิ่มเติม และขอบเขตงานให้ยืนยันในใบเสนอราคาอย่างเป็นทางการ','These are preliminary estimates. Confirm taxes, extra costs and scope in a formal quotation.')}</p></div></section>'''
(ROOT/'pricing.html').write_text(shell('ราคาและแพ็กเกจ Payroll / Recruitment',hub,'pricing.html','ประเมินค่าบริการเงินเดือนและสรรหาบุคลากร เปรียบเทียบแพ็กเกจและคำนวณราคาได้ในที่เดียว'),encoding='utf-8')
script='<script src="assets/pricing-model.js?v=6" defer></script><script src="assets/calculators.js?v=6" defer></script>'
note=t('ราคาเป็นการประเมินเบื้องต้น ภาษี ค่าใช้จ่ายเพิ่มเติม และเงื่อนไขให้ยืนยันกับทีมงานก่อนเริ่มบริการ','Preliminary estimate. Confirm taxes, extra costs and conditions with the team before starting.','p','estimate-note')
plans=''.join(f'''<label class="plan-choice"><input type="radio" name="payroll-plan" value="{k}" {'checked' if k=='lite' else ''}><span class="plan-choice-body"><strong>{n}</strong>{t(th,en,'small')}<span class="plan-price" data-plan-price="{k}">—</span></span></label>''' for k,n,th,en in [('lite','Lite','เงินเดือนและรายงานพื้นฐาน','Payroll & core reports'),('pro','Pro','เพิ่มทะเบียนพนักงานและรายงานสิ้นปี','Employee records & year-end reports'),('premium','Premium','เพิ่มเวลาทำงานและงานบุคคล','Attendance & extended HR support')])
feature_en=['Salary, wages and overtime calculation','Social security, provident fund and withholding calculations','Payroll and bank summary reports','Monthly withholding report','Social security filing documents','Monthly tax and social security submission','Payslip format','Employee records','Social security joiners and leavers','Provident fund joiners and leavers','Year-end certificates and reports','Salary and employment certificates','Attendance data review','Attendance summary']
rows=[]
for idx,row in enumerate(json.loads((ROOT/'scripts/site-data/payroll-features.json').read_text(encoding='utf-8'))):
    cells=''.join('<td>'+('✓' if x=='✓' else t('ไม่รวม','Not included') if x=='✗' else t(x, 'Standard payslip' if idx==6 and i==0 else 'Carbon / online PDF' if idx==6 and i==1 else 'Carbon / password-protected PDF' if idx==6 else x))+'</td>' for i,x in enumerate(row[1:]))
    rows.append(f'<tr><th scope="row">{t(re.sub(r"^\d+\.\s*","",row[0]),feature_en[idx])}</th>{cells}</tr>')
pay=f'''{backbar('Payroll')}{hero('PAYROLL CALCULATOR','คำนวณราคา Payroll','Payroll cost calculator','เลือกจำนวนพนักงานและขอบเขตที่ต้องการ ระบบจะแสดงวิธีคิดราคาให้เห็นทีละส่วน','Choose headcount and scope. See exactly how the estimate is calculated.')}<section class="calculator-section"><div class="ms-container">{service_switch('payroll')}<div class="calculator-layout" data-calculator="payroll"><div class="calculator-inputs"><div class="calc-step"><div class="step-title"><span>01</span>{t('บริษัทของคุณมีพนักงานกี่คน?','How many employees do you have?','h2')}</div><label class="number-field" for="pax">{t('จำนวนพนักงาน','Employee count')}<span><input id="pax" type="number" min="1" max="1000000" step="1" value="30" inputmode="numeric" aria-describedby="pax-error"><b>{t('คน','people')}</b></span></label><div class="preset-counts" aria-label="Headcount examples">{''.join(f'<button type="button" data-headcount="{n}">{n} '+t('คน','people')+'</button>' for n in [10,30,100,300])}</div><p id="pax-error" class="calc-error" role="status" hidden>{t('กรุณากรอกจำนวนเต็มตั้งแต่ 1 ถึง 1,000,000 คน','Enter a whole number between 1 and 1,000,000.')}</p></div>
<div class="calc-step"><div class="step-title"><span>02</span>{t('เลือกแพ็กเกจที่เหมาะกับงาน','Choose your service scope','h2')}</div><fieldset class="plan-options"><legend class="visually-hidden">Payroll package</legend>{plans}</fieldset><a class="ms-text-link" href="#scope-compare">{t('เปรียบเทียบขอบเขตทั้ง 3 แพ็กเกจ','Compare all three packages')} ↓</a></div></div>
<aside class="estimate-panel" aria-label="Payroll estimate"><div class="estimate-title"><span class="ms-eyebrow">YOUR ESTIMATE</span><span id="selected-payroll-plan" class="estimate-plan">Lite</span></div>{t('ค่าบริการประมาณการ','Estimated service fee','h2')}<div class="estimate-total"><strong id="payroll-total">—</strong><span>{t('บาท / เดือน','THB / month')}</span></div><dl class="cost-breakdown"><div><dt>{t('ค่าบริการ 30 คนแรก','Base fee: first 30 employees')}</dt><dd id="payroll-base">—</dd></div><div><dt id="payroll-extra-label">—</dt><dd id="payroll-extra">—</dd></div><div class="annual-row"><dt>{t('ประมาณการ 12 เดือน','12-month estimate')}</dt><dd id="payroll-annual">—</dd></div></dl><p class="formula-note" id="payroll-formula"></p><a class="ms-btn" id="payroll-quote" href="request-quotation.html?service=payroll-outsourcing">{t('ขอใบเสนอราคาแพ็กเกจนี้','Request this package')} ↗</a>{note}<p class="calc-announcement visually-hidden" id="payroll-announcement" role="status" aria-live="polite"></p></aside></div>
<details class="calculator-details" id="scope-compare"><summary>{t('เปรียบเทียบสิ่งที่รวมในแต่ละแพ็กเกจ','Compare what each package includes')} <span>＋</span></summary><div class="price-table-wrap" tabindex="0" aria-label="Payroll package comparison"><table class="price-table"><thead><tr><th>{t('ขอบเขตงาน','Scope')}</th><th>Lite</th><th>Pro</th><th>Premium</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div></details>
<details class="calculator-details"><summary>{t('ดูอัตราและวิธีคำนวณ','View rates and calculation method')} <span>＋</span></summary><div class="details-content"><p>{t('30 คนแรกคิดราคาเหมา ส่วนที่เกินใช้จำนวนคนที่เกิน 30 คูณอัตราของช่วงจำนวนพนักงานทั้งหมด ไม่ใช่อัตราขั้นบันไดสะสม','The first 30 employees use a flat fee. Additional headcount is multiplied by the rate for the total-headcount band; this is not progressive tier pricing.')}</p><div class="price-table-wrap"><table class="price-table"><thead><tr><th>{t('จำนวนพนักงานทั้งหมด','Total headcount')}</th><th>Lite</th><th>Pro</th><th>Premium</th></tr></thead><tbody><tr><th>1–30</th><td>5,000</td><td>10,000</td><td>15,000</td></tr><tr><th>31–200</th><td>80</td><td>100</td><td>120</td></tr><tr><th>201–500</th><td>65</td><td>90</td><td>100</td></tr><tr><th>501+</th><td>50</td><td>70</td><td>80</td></tr></tbody></table></div><p class="ms-note">{t('แถวแรก: บาท/เดือน · แถวถัดไป: บาท/คนที่เกิน/เดือน อัตราที่ลดลงเมื่อเปลี่ยนช่วงอาจทำให้ยอดรวมลดลง ระบบคงวิธีคิดตามตารางบริการเดิม','First row: THB/month. Other rows: THB/additional employee/month. A lower rate at a new band can reduce the total; the existing published pricing method is retained.')}</p></div></details><div class="calc-bottom-nav"><a href="pricing.html">← {t('กลับหน้าราคารวม','Back to all pricing')}</a><a href="recruitment-calculator.html">{t('คำนวณค่าบริการสรรหาคน','Calculate recruitment costs')} →</a></div></div></section>'''
(ROOT/'payroll-calculator.html').write_text(shell('คำนวณค่าบริการ Payroll',pay,'payroll-calculator.html','คำนวณราคา Payroll จากจำนวนพนักงาน เปรียบเทียบ Lite Pro Premium และดูวิธีคิดราคา',script),encoding='utf-8')
retainers=''.join(f'<label class="plan-choice"><input type="radio" name="retainer-plan" value="{key}" '+('checked' if key=='starter' else '')+f'><span class="plan-choice-body"><strong>{name}</strong>{t(f"สูงสุด {pos} ตำแหน่งพร้อมกัน · {cv} ผู้ผ่านคัดกรอง/เดือน",f"Up to {pos} active roles · {cv} qualified candidates/month","small")}<span class="plan-price">{cost:,} '+t('บาท/เดือน','THB/month')+'</span></span></label>' for key,name,pos,cv,cost in [('starter','Starter',2,15,9900),('professional','Professional',3,25,17900),('business','Business',5,40,24900)])
rec=f'''{backbar('Recruitment')}{hero('RECRUITMENT CALCULATOR','คำนวณค่าบริการสรรหาคน','Recruitment cost calculator','รับคนต่อเนื่องหรือเปิดเฉพาะบางตำแหน่ง เลือกรูปแบบที่เหมาะกับการจ้างของคุณ','Hiring continuously or filling a specific role? Choose the model that fits your needs.')}<section class="calculator-section"><div class="ms-container">{service_switch('recruitment')}<div class="calculator-layout" data-calculator="recruitment"><div class="calculator-inputs"><div class="calc-step"><div class="step-title"><span>01</span>{t('เลือกรูปแบบบริการ','Choose a pricing model','h2')}</div><fieldset class="recruitment-modes"><legend class="visually-hidden">Recruitment pricing model</legend><label><input type="radio" name="recruitment-mode" value="retainer" checked><span><strong>{t('เหมารายเดือน','Monthly retainer')}</strong>{t('สำหรับการรับคนอย่างต่อเนื่อง','For an ongoing hiring pipeline','small')}</span></label><label><input type="radio" name="recruitment-mode" value="success"><span><strong>Success Fee</strong>{t('จ่ายเมื่อผู้สมัครเริ่มงาน','Pay when the candidate starts','small')}</span></label></fieldset></div>
<div class="calc-step" id="retainer-inputs"><div class="step-title"><span>02</span>{t('เลือกแพ็กเกจรายเดือน','Choose a monthly package','h2')}</div><fieldset class="plan-options"><legend class="visually-hidden">Retainer package</legend>{retainers}</fieldset><p class="ms-note">{t('จำนวนผู้ผ่านคัดกรองเป็นขอบเขตการนำเสนอ ไม่ใช่จำนวนคนที่รับประกันว่าจะจ้างได้ ตำแหน่งเกินแพ็กเกจให้ทีมงานประเมินเพิ่ม','Qualified-candidate limits describe submissions, not guaranteed hires. Ask for an additional quote for roles beyond the package.')}</p><a class="ms-text-link" href="recruitment.html#additional">{t('ดูบริการเสริมและเงื่อนไข','View extras and conditions')} ↗</a></div>
<div class="calc-step" id="success-inputs" hidden><div class="step-title"><span>02</span>{t('กรอกข้อมูลตำแหน่งงาน','Enter the role details','h2')}</div><label class="calc-field">{t('ระดับตำแหน่ง','Role level')}<select id="role-level"><option value="general">General — 15%</option><option value="specialist">Specialist / Professional — 18%</option><option value="manager">Manager — 20%</option><option value="executive">Executive / Headhunting — 25%</option></select></label><div class="calc-two-fields"><label class="calc-field">{t('เงินเดือนต่อคน (บาท/เดือน)','Salary per person (THB/month)')}<input id="hire-salary" type="number" value="30000" min="0.01" max="10000000" step="0.01" inputmode="decimal" aria-describedby="recruitment-error"></label><label class="calc-field">{t('รายได้อื่นต่อคน (บาท/ปี)','Other income per person (THB/year)')}<input id="hire-other" type="number" value="0" min="0" max="100000000" step="0.01" inputmode="decimal" aria-describedby="recruitment-error"></label></div><label class="calc-field">{t('จำนวนผู้เริ่มงานที่ใช้รายได้และระดับเดียวกัน','Number of hires with the same income and level')}<input id="hire-count" type="number" value="1" min="1" max="1000" step="1" inputmode="numeric" aria-describedby="recruitment-error"></label><p class="ms-note">{t('รายได้รวมต่อปี = เงินเดือน × 12 + รายได้อื่นต่อปี หากแต่ละคนมีรายได้ต่างกัน ให้คำนวณแยกครั้ง','Annual income = monthly salary × 12 + other annual income. Calculate separately when candidates have different incomes.')}</p><p id="recruitment-error" class="calc-error" role="status" hidden>{t('ตรวจข้อมูล: เงินเดือนต้องมากกว่า 0 รายได้อื่นต้องไม่ติดลบ (ทศนิยมไม่เกิน 2 ตำแหน่ง) และจำนวนคนต้องเป็นจำนวนเต็ม 1–1,000','Check inputs: salary must be positive, other income non-negative (up to 2 decimals), and hires a whole number from 1–1,000.')}</p></div></div>
<aside class="estimate-panel" aria-label="Recruitment estimate"><div class="estimate-title"><span class="ms-eyebrow">YOUR ESTIMATE</span><span class="estimate-plan" id="recruitment-plan">Starter</span></div><h2 id="recruitment-heading">{t('ค่าบริการรายเดือน','Monthly service fee')}</h2><div class="estimate-total"><strong id="recruitment-total">—</strong><span id="recruitment-unit">{t('บาท / เดือน','THB / month')}</span></div><dl class="cost-breakdown" id="recruitment-breakdown"></dl><p class="formula-note" id="recruitment-formula"></p><a class="ms-btn" id="recruitment-quote" href="request-quotation.html?service=recruitment">{t('ขอใบเสนอราคาสรรหาคน','Request a recruitment quote')} ↗</a>{note}<p class="visually-hidden" id="recruitment-announcement" role="status" aria-live="polite"></p></aside></div>
<div class="pricing-help">{icon('doc')}<div>{t('มีตำแหน่งที่ซับซ้อน หรือต้องการหลายระดับ?','Complex roles or a mix of seniority levels?','h3')}{t('ส่งรายละเอียดตำแหน่งให้ทีมประเมิน เงื่อนไขการทดแทนและโปรโมชันต้องยืนยันก่อนเริ่มบริการ','Send a hiring brief for an assessment. Confirm replacement and promotional terms before starting.','p')}</div>{btn('ดูขอบเขตและเงื่อนไข','Service scope & terms','recruitment.html',True)}</div><div class="calc-bottom-nav"><a href="pricing.html">← {t('กลับหน้าราคารวม','Back to all pricing')}</a><a href="payroll-calculator.html">{t('คำนวณค่าบริการ Payroll','Calculate payroll costs')} →</a></div></div></section>'''
(ROOT/'recruitment-calculator.html').write_text(shell('คำนวณค่าบริการสรรหาบุคลากร',rec,'recruitment-calculator.html','ประเมินค่าบริการ Recruitment แบบเหมารายเดือนและ Success Fee ตามระดับตำแหน่งและรายได้ต่อปี',script),encoding='utf-8')
