from site_helpers import *

def recruitment_comparison():
    source=(ROOT/'recruitment.html').read_text(encoding='utf-8-sig')
    table=re.search(r'<table class="compare">.*?</table>',source,re.S).group(0)
    table=table.replace('class="compare"','class="price-table"').replace('<th>Service</th>','<th scope="col">'+t('ขอบเขตงาน','Scope')+'</th>').replace('<td>ราคา / เดือน</td>','<td>'+t('ค่าบริการ / เดือน (บาท)','Monthly fee (THB)')+'</td>')
    table=table.replace('<td>Active Positions</td>','<td>'+t('ตำแหน่งที่เปิดพร้อมกัน (สูงสุด)','Concurrent active roles (up to)')+'</td>').replace('<td>Qualified Candidates</td>','<td>'+t('ผู้ผ่านคัดกรอง / เดือน (สูงสุด)','Qualified candidates / month (up to)')+'</td>')
    table=re.sub(r'<tr><td>(.*?)</td>',r'<tr><th scope="row">\1</th>',table)
    extra='<tr><th scope="row">'+t('ระยะทดแทนตามเงื่อนไข (วัน)','Conditional replacement period (days)')+'</th><td>30</td><td>60</td><td>90</td></tr><tr><th scope="row">'+t('งบสื่อประกาศงาน / เดือน (บาท สูงสุด)','Media support / month (THB, up to)')+'</th><td>0</td><td>2,000</td><td>4,000</td></tr>'
    table=table.replace('</tbody>',extra+'</tbody>')
    rates=''.join('<tr><th scope="row">'+name+'</th><td>'+str(rate)+'%</td></tr>' for name,rate in [('General',15),('Specialist / Professional',18),('Manager',20),('Executive / Headhunting',25)])
    return '<section class="payroll-comparison recruitment-comparison" id="scope-compare" aria-labelledby="recruitment-compare-title"><div class="payroll-compare-heading"><span class="ms-eyebrow">COMPARE PACKAGES</span><h2 id="recruitment-compare-title">'+t('เปรียบเทียบสิ่งที่รวมในแต่ละแพ็กเกจ','Compare what each package includes')+'</h2><p>'+t('เปรียบเทียบแพ็กเกจสรรหาแบบเหมารายเดือน Starter, Professional และ Business ในตารางเดียว','Compare the Starter, Professional and Business monthly recruitment retainers side by side.')+'</p></div><div class="price-table-wrap" tabindex="0" aria-label="Monthly recruitment package comparison">'+table+'</div><p class="ms-note">'+t('แสดงราคาปกติ จำนวนผู้ผ่านคัดกรองไม่ใช่จำนวนการจ้างที่รับประกัน การทดแทนและงบสื่อเป็นไปตามเงื่อนไขของแพ็กเกจ','Standard prices shown. Candidate submissions are not guaranteed hires. Replacement and media support follow package terms.')+' <a href="recruitment.html#compare">'+t('รายละเอียดบริการและเงื่อนไข','Service details and terms')+' ↗</a></p></section><details class="calculator-details" id="success-rates"><summary>'+t('ดูอัตราและวิธีคำนวณ Success Fee','View success fee rates and calculation')+' <span>＋</span></summary><div class="details-content"><p>'+t('ใช้สำหรับแบบจ่ายเมื่อผู้สมัครเริ่มงาน โดยคำนวณแยกจากแพ็กเกจเหมารายเดือน','For success-based hiring, payable when the candidate starts. Calculated separately from monthly retainers.')+'</p><div class="price-table-wrap" tabindex="0" aria-label="Success fee rates"><table class="price-table"><thead><tr><th>'+t('ระดับตำแหน่ง','Role level')+'</th><th>'+t('อัตราจากรายได้รวมต่อปี','Rate on annual income')+'</th></tr></thead><tbody>'+rates+'</tbody></table></div><p>'+t('ค่าบริการ = (เงินเดือน × 12 + รายได้อื่นต่อปี) × อัตราตามระดับ × จำนวนผู้เริ่มงานที่ใช้รายได้เดียวกัน','Fee = (monthly salary × 12 + other annual income) × role rate × hires with the same income.')+'</p><p class="ms-note">'+t('หากรายได้หรือระดับตำแหน่งต่างกัน ให้คำนวณแยก ภาษีและค่าใช้จ่ายเพิ่มเติมให้ยืนยันในใบเสนอราคา','Calculate separately for different incomes or role levels. Confirm taxes and additional charges in the quotation.')+'</p></div></details>'
